version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  app:
    build: .
    container_name: rag_app
    depends_on:
      - qdrant
      - ollama
    volumes:
      - ./data:/app/data
      - ./hashes.db:/app/hashes.db
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434  
      - OLLAMA_MODEL=llama3            
    ports:
      - "8000:8000"
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
